"""Add degree_level to Scholarship table

Revision ID: 1c7e84d3cfdb
Revises: 281d771498e9
Create Date: 2024-12-23 15:57:51.045511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7e84d3cfdb'
down_revision: Union[str, None] = '281d771498e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('degree_level', sa.Enum('bachelor', 'master', 'doctorate', name='degree_level'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'degree_level')
    # ### end Alembic commands ###
