"""Redesign News model

Revision ID: 281d771498e9
Revises: f57ad19d95df
Create Date: 2024-12-23 13:34:18.684808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '281d771498e9'
down_revision: Union[str, None] = 'f57ad19d95df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('body', sa.Text(), nullable=True))
    op.drop_column('news', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('news', 'body')
    op.drop_column('news', 'description')
    # ### end Alembic commands ###
