"""Fix degree_level enum value naming

Revision ID: 2bb25afe1334
Revises: fd5f83f670ea
Create Date: 2024-12-24 12:16:15.747450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bb25afe1334'
down_revision: Union[str, None] = 'fd5f83f670ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholarships', 'degree_level',
               existing_type=mysql.ENUM('bachelors', 'masters', 'doctorate'),
               type_=sa.Enum('bachelor', 'master', 'doctorate', name='degree_level'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholarships', 'degree_level',
               existing_type=sa.Enum('bachelor', 'master', 'doctorate', name='degree_level'),
               type_=mysql.ENUM('bachelors', 'masters', 'doctorate'),
               existing_nullable=True)
    # ### end Alembic commands ###
