"""Add times_updated field

Revision ID: a42eda2c0de8
Revises: 2bb25afe1334
Create Date: 2024-12-24 12:33:57.373988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42eda2c0de8'
down_revision: Union[str, None] = '2bb25afe1334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('times_updated', sa.Integer(), nullable=True))
    op.add_column('scholarships', sa.Column('times_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'times_updated')
    op.drop_column('news', 'times_updated')
    # ### end Alembic commands ###
