"""Allow degree_level to be nullable

Revision ID: fd5f83f670ea
Revises: b1b5d64562c5
Create Date: 2024-12-23 18:51:57.214939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd5f83f670ea'
down_revision: Union[str, None] = 'b1b5d64562c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholarships', 'degree_level',
               existing_type=mysql.ENUM('bachelor', 'master', 'doctorate'),
               type_=sa.Enum('bachelors', 'masters', 'doctorate', name='degree_level'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholarships', 'degree_level',
               existing_type=sa.Enum('bachelors', 'masters', 'doctorate', name='degree_level'),
               type_=mysql.ENUM('bachelor', 'master', 'doctorate'),
               nullable=False)
    # ### end Alembic commands ###
